apiVersion: v1
kind: Namespace
metadata:
  name: envoy-initializer
  labels:
    app: envoy-initializer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoy-initializer:default
  labels:
    app: envoy-initializer
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: envoy-initializer
  name: config-watcher
  labels:
    app: envoy-initializer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envoy-initializer:default
  labels:
    app: envoy-initializer
subjects:
- kind: ServiceAccount
  name: default
  namespace: envoy-initializer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
#  name: envoy-initializer:default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: envoy-initializer
  name: config-watcher
  labels:
    app: envoy-initializer
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-watcher
